# Dataset_understanding
### Purpose:
- Understand dataset structure, columns, datatypes, missing values.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/leetcode_dataset - lc.csv")

In [2]:
df.head()

,id,title,description,is_premium,difficulty,solution_link,acceptance_rate,frequency,url,discuss_count,accepted,submissions,companies,related_topics,likes,dislikes,rating,asked_by_faang,similar_questions
0,1,Two Sum,Given an array of integers `nums` and an integ...,0,Easy,/articles/two-sum,46.7,100.0,https://leetcode.com/problems/two-sum,999,4.1M,8.7M,"Amazon,Google,Apple,Adobe,Microsoft,Bloomberg,...","Array,Hash Table",20217,712,97,1,"[3Sum, /problems/3sum/, Medium], [4Sum, /probl..."
1,2,Add Two Numbers,You are given two non-empty linked lists repre...,0,Medium,/articles/add-two-numbers,35.7,93.1,https://leetcode.com/problems/add-two-numbers,999,1.9M,5.2M,"Bloomberg,Microsoft,Amazon,Google,Facebook,App...","Linked List,Math,Recursion",11350,2704,81,1,"[Multiply Strings, /problems/multiply-strings/..."
2,3,Longest Substring Without Repeating Characters,"Given a string `s`, find the length of the lon...",0,Medium,/articles/longest-substring-without-repeating-...,31.5,90.9,https://leetcode.com/problems/longest-substrin...,999,2.1M,6.7M,"Amazon,Bloomberg,Microsoft,Facebook,Apple,Adob...","Hash Table,Two Pointers,String,Sliding Window",13810,714,95,1,[Longest Substring with At Most Two Distinct C...
3,4,Median of Two Sorted Arrays,Given two sorted arrays `nums1` and `nums2` of...,0,Hard,/articles/median-of-two-sorted-arrays,31.4,86.2,https://leetcode.com/problems/median-of-two-so...,999,904.7K,2.9M,"Amazon,Goldman Sachs,Facebook,Microsoft,Apple,...","Array,Binary Search,Divide and Conquer",9665,1486,87,1,NaN
4,5,Longest Palindromic Substring,"Given a string `s`, return the longest palindr...",0,Medium,/articles/longest-palindromic-substring,30.6,84.7,https://leetcode.com/problems/longest-palindro...,999,1.3M,4.1M,"Amazon,Microsoft,Wayfair,Facebook,Adobe,eBay,G...","String,Dynamic Programming",10271,670,94,1,"[Shortest Palindrome, /problems/shortest-palin..."

In [3]:
df.tail()

,id,title,description,is_premium,difficulty,solution_link,acceptance_rate,frequency,url,discuss_count,accepted,submissions,companies,related_topics,likes,dislikes,rating,asked_by_faang,similar_questions
1820,1821,Find Customers With Positive Revenue this Year,SQL Schema,1,Easy,NaN,88.9,0.0,https://leetcode.com/problems/find-customers-w...,15,305,343,Google,NaN,2,2,50,1,NaN
1821,1822,Sign of the Product of an Array,There is a function `signFunc(x)` that returns...,0,Easy,NaN,67.8,0.0,https://leetcode.com/problems/sign-of-the-prod...,104,7.9K,11.7K,Microsoft,Math,37,4,90,0,NaN
1822,1823,Find the Winner of the Circular Game,There are `n` friends that are playing a game....,0,Medium,NaN,71.8,0.0,https://leetcode.com/problems/find-the-winner-...,135,6.8K,9.5K,Bloomberg,Array,81,4,95,0,NaN
1823,1824,Minimum Sideway Jumps,There is a 3 lane road of length `n` that cons...,0,Medium,NaN,47.2,0.0,https://leetcode.com/problems/minimum-sideway-...,134,5K,10.7K,Pony.ai,"Dynamic Programming,Breadth-first Search",147,8,95,0,"[Frog Jump, /problems/frog-jump/, Hard]"
1824,1825,Finding MK Average,"You are given two integers, `m` and `k`, and a...",0,Hard,NaN,28.1,0.0,https://leetcode.com/problems/finding-mk-average,48,2.1K,7.4K,Google,"Heap,Design,Queue",52,43,55,1,"[Find Median from Data Stream, /problems/find-..."

In [3]:
df.shape

(1825, 19)

In [4]:
df.columns

Index(['id', 'title', 'description', 'is_premium', 'difficulty',
       'solution_link', 'acceptance_rate', 'frequency', 'url', 'discuss_count',
       'accepted', 'submissions', 'companies', 'related_topics', 'likes',
       'dislikes', 'rating', 'asked_by_faang', 'similar_questions'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1825 non-null   int64
 1   title              1825 non-null   str
 2   description        1825 non-null   str
 3   is_premium         1825 non-null   int64
 4   difficulty         1825 non-null   str
 5   solution_link      987 non-null    str
 6   acceptance_rate    1825 non-null   float64
 7   frequency          1825 non-null   float64
 8   url                1825 non-null   str
 9   discuss_count      1825 non-null   int64
 10  accepted           1825 non-null   str
 11  submissions        1825 non-null   str
 12  companies          1749 non-null   str
 13  related_topics     1571 non-null   str
 14  likes              1825 non-null   int64
 15  dislikes           1825 non-null   int64
 16  rating             1825 non-null   int64
 17  asked_by_faang     1825 non-null   int64
 18  similar_questions  745 non-null    str
dtypes: float64(2), int64(7), str(10)
memory usage: 271.0 KB

In [6]:
df.describe(include="all")

,id,title,description,is_premium,difficulty,solution_link,acceptance_rate,frequency,url,discuss_count,accepted,submissions,companies,related_topics,likes,dislikes,rating,asked_by_faang,similar_questions
count,1825.000000,1825,1825,1825.000000,1825,987,1825.000000,1825.000000,1825,1825.000000,1825,1825,1749,1571,1825.000000,1825.000000,1825.000000,1825.000000,745
unique,NaN,1825,1670,NaN,3,987,NaN,NaN,1825,NaN,1098,1236,691,320,NaN,NaN,NaN,NaN,689
top,NaN,Two Sum,SQL Schema,NaN,Medium,/articles/two-sum,NaN,NaN,https://leetcode.com/problems/two-sum,NaN,2.1K,1.2M,Google,Array,NaN,NaN,NaN,NaN,"[Combination Sum, /problems/combination-sum/, ..."
freq,NaN,1,156,NaN,963,1,NaN,NaN,1,NaN,8,16,257,134,NaN,NaN,NaN,NaN,4
mean,913.000000,NaN,NaN,0.218082,NaN,NaN,53.139616,21.113041,NaN,421.435068,NaN,NaN,NaN,NaN,1050.534795,279.010959,77.391233,0.671233,NaN
std,526.976438,NaN,NaN,0.413057,NaN,NaN,14.778411,22.364741,NaN,330.583617,NaN,NaN,NaN,NaN,1512.674013,608.489206,23.317515,0.469894,NaN
min,1.000000,NaN,NaN,0.000000,NaN,NaN,13.900000,0.000000,NaN,9.000000,NaN,NaN,NaN,NaN,2.000000,0.000000,7.000000,0.000000,NaN
25%,457.000000,NaN,NaN,0.000000,NaN,NaN,42.400000,3.100000,NaN,150.000000,NaN,NaN,NaN,NaN,217.000000,32.000000,67.000000,0.000000,NaN
50%,913.000000,NaN,NaN,0.000000,NaN,NaN,51.600000,13.500000,NaN,292.000000,NaN,NaN,NaN,NaN,516.000000,92.000000,88.000000,1.000000,NaN
75%,1369.000000,NaN,NaN,0.000000,NaN,NaN,62.800000,31.800000,NaN,663.000000,NaN,NaN,NaN,NaN,1200.000000,239.000000,95.000000,1.000000,NaN
max,1825.000000,NaN,NaN,1.000000,NaN,NaN,95.600000,100.000000,NaN,999.000000,NaN,NaN,NaN,NaN,20217.000000,8900.000000,100.000000,1.000000,NaN

In [7]:
df.isnull().sum()

id                      0
title                   0
description             0
is_premium              0
difficulty              0
solution_link         838
acceptance_rate         0
frequency               0
url                     0
discuss_count           0
accepted                0
submissions             0
companies              76
related_topics        254
likes                   0
dislikes                0
rating                  0
asked_by_faang          0
similar_questions    1080
dtype: int64

### Theory
- Dataset contains LeetCode problem information.
- Check total rows and columns.
- Understand datatypes.
- Find missing values.
- Observe important features